# Generated by Django 4.2.2 on 2023-07-01 17:50

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=["middle", "center"],
                        default="default_land.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[2878, 1618],
                        upload_to="category_landscape",
                    ),
                ),
                ("altText", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards_gallery.card",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards_gallery.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="cards",
            field=models.ManyToManyField(
                through="cards_gallery.CardItem", to="cards_gallery.card"
            ),
        ),
    ]
