# Generated by Django 4.2.2 on 2023-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0002_card_carditem_category_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
