# Generated by Django 4.2.2 on 2023-07-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0003_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="audio",
            field=models.FileField(default="default_audio.mp3", upload_to="audio"),
        ),
    ]
