# Generated by Django 4.2.2 on 2023-07-09 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0004_card_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carditem",
            name="card",
        ),
        migrations.RemoveField(
            model_name="carditem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="category",
            name="cards",
        ),
        migrations.AddField(
            model_name="card",
            name="cards",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="cards_gallery.CardItem",
                to="cards_gallery.card",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="carditem",
            name="child",
            field=models.ForeignKey(
                blank=True,
                db_column="child_card",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="child_card",
                to="cards_gallery.card",
            ),
        ),
        migrations.AddField(
            model_name="carditem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_card",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="parent_card",
                to="cards_gallery.card",
            ),
        ),
    ]
