# Generated by Django 4.2.2 on 2023-07-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cards_gallery",
            "0005_remove_carditem_card_remove_carditem_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_category",
            field=models.BooleanField(default=False),
        ),
    ]
