# Generated by Django 4.2.2 on 2023-07-09 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0006_card_is_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
