# Generated by Django 4.2.2 on 2023-07-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0007_delete_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScavengerCardTest",
            fields=[
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="cards_gallery.card",
                    ),
                ),
            ],
        ),
    ]
