# Generated by Django 4.2.2 on 2023-07-15 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0008_scavengercardtest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScavengerCardTest",
        ),
    ]
