# Generated by Django 4.2.2 on 2023-07-19 15:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0016_alter_card_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                default="default_image.jpg",
                force_format=None,
                keep_meta=True,
                quality=75,
                scale=None,
                size=[1400, 1000],
                upload_to="image",
            ),
        ),
    ]
