# Generated by Django 4.2.2 on 2023-07-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0019_remove_cardtag_card_card_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardtag",
            name="card_pk",
            field=models.ForeignKey(
                blank=True,
                db_column="card_pk",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_pk",
                to="cards_gallery.card",
            ),
        ),
    ]
