# Generated by Django 4.2.2 on 2023-07-25 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0020_cardtag_card_pk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="cardtag",
            name="card_pk",
        ),
    ]
