# Generated by Django 4.2.2 on 2023-07-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0023_publication_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardtag",
            name="card_fk",
        ),
        migrations.AddField(
            model_name="card",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, to="cards_gallery.cardtag"
            ),
        ),
    ]
