# Generated by Django 4.2.2 on 2023-07-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cards_gallery",
            "0025_remove_card_tags_cardtag_card_fk_delete_article_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, to="cards_gallery.cardtag"
            ),
        ),
    ]
