# Generated by Django 4.2.2 on 2023-08-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards_gallery", "0031_remove_card_alttext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tags", to="cards_gallery.cardtag"
            ),
        ),
    ]
