# Generated by Django 4.2.2 on 2023-08-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards_games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gametype",
            name="template_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
