# Generated by Django 4.2.2 on 2023-08-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards_games", "0002_gametype_template_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gametype",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
