# Generated by Django 4.2.2 on 2023-08-07 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards_games", "0003_alter_gametype_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gametype",
            name="image",
        ),
    ]
