# Generated by Django 4.2.2 on 2023-08-07 21:38

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("cards_games", "0004_remove_gametype_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="gametype",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                default="default_image.jpg",
                force_format=None,
                keep_meta=True,
                quality=75,
                scale=None,
                size=[1400, 1000],
                upload_to="image",
            ),
        ),
    ]
