# Generated by Django 4.2.2 on 2023-07-19 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_settings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="with_autoplay",
            new_name="autoplay_sound",
        ),
    ]
