# Generated by Django 4.2.2 on 2023-08-01 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_settings", "0004_usersetting_delete_usersettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersetting",
            name="autoplay_sound",
        ),
    ]
