# Generated by Django 4.2.2 on 2023-08-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_settings", "0005_remove_usersetting_autoplay_sound"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersetting",
            name="default_game_query",
            field=models.CharField(default="", max_length=100),
        ),
    ]
